/*
 * Copyright 2025 European Union
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the European
 * Commission – subsequent versions of the EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence
 * is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the Licence for the specific language governing permissions and limitations under
 * the Licence.
 */
package eu.europa.ted.eforms.sdk.schematron;

import java.util.List;

import eu.europa.ted.efx.model.Context;
import eu.europa.ted.efx.model.rules.RuleNature;
import eu.europa.ted.efx.model.rules.ValidationRule;
import eu.europa.ted.efx.model.variables.DynamicVariable;

/**
 * Represents a Schematron &lt;report&gt; element.
 * Fires when the test expression evaluates to true.
 * For rules referencing dynamic variables, the test is guarded so that errors
 * do not cause the main rule to fire — a companion NoApiError assert handles that.
 */
public class SchematronReport extends SchematronTest {

  private final List<DynamicVariable> dynamicVariables;

  public SchematronReport(final ValidationRule rule, final Context ruleContext) {
    super(rule, ruleContext);
    this.dynamicVariables = rule.findReferencedDynamicVariables();
  }

  @Override
  public RuleNature getRuleNature() {
    if (!this.dynamicVariables.isEmpty()) {
      return RuleNature.DYNAMIC;
    }
    return super.getRuleNature();
  }

  @Override
  public String getElementName() {
    return "report";
  }

  @Override
  public String getTest() {
    String baseTest = super.getTest();
    if (this.getRuleNature() != RuleNature.DYNAMIC) {
      return baseTest;
    }
    // A report fires when the test is true. Prepending "not($var = -1) and" makes the
    // test false when any dynamic variable errored, preventing the main report from firing.
    // Companion NoApiError asserts handle errors separately.
    StringBuilder sb = new StringBuilder();
    for (var variable : this.dynamicVariables) {
      sb.append("not($").append(variable.name).append(" = -1) and ");
    }
    for (var variable : this.rule.getAutoGeneratedVariables()) {
      sb.append("not($").append(variable.name).append(" = -1) and ");
    }
    // Always wrap baseTest: the "and" guards bind tighter than any "or" in the expression.
    sb.append("(").append(baseTest).append(")");
    return sb.toString();
  }
}
