/*
 * Copyright 2025 European Union
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the European
 * Commission – subsequent versions of the EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence
 * is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the Licence for the specific language governing permissions and limitations under
 * the Licence.
 */
package eu.europa.ted.eforms.sdk.schematron;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Predicate;
import java.util.stream.Collectors;

import eu.europa.ted.efx.model.Context;
import eu.europa.ted.efx.model.rules.RuleNature;
import eu.europa.ted.efx.model.rules.ReportRule;
import eu.europa.ted.efx.model.rules.RuleSet;
import eu.europa.ted.efx.model.rules.ValidationRule;
import eu.europa.ted.efx.model.variables.DynamicVariable;

/**
 * Represents a Schematron &lt;rule&gt; element.
 */
public class SchematronRule {
  private final List<SchematronLet> letElements;
  private final List<SchematronLet> promotedLetElements;
  private final List<SchematronTest> tests;
  private final Context context;

  SchematronRule(final RuleSet ruleSet, final Predicate<ValidationRule> applicableRules) {
    this.context = ruleSet.getContext();

    this.tests = this.createTests(ruleSet, applicableRules);

    this.letElements = ruleSet.getLocalVariables().stream()
        .map(SchematronLet::new)
        .collect(Collectors.toCollection(ArrayList::new));

    // WITH-before-context variables promoted to pattern scope (see TEDEFO-4986)
    this.promotedLetElements = ruleSet.getPromotedVariables().stream()
        .map(SchematronLet::new)
        .collect(Collectors.toList());
  }

  private List<SchematronTest> createTests(final RuleSet ruleSet,
      final Predicate<ValidationRule> applicableRules) {

    List<SchematronTest> tests = ruleSet.stream()
        .filter(applicableRules)
        .flatMap(rule -> this.createTests(rule).stream())
        .collect(Collectors.toCollection(ArrayList::new));

    ValidationRule fallback = ruleSet.getFallbackRule();
    if (fallback != null && applicableRules.test(fallback)) {
      tests.addAll(this.createTests(fallback));
    }
    return tests;
  }

  private List<SchematronTest> createTests(final ValidationRule rule) {

    // Error asserts for all dynamic variables (declared and auto-generated).
    List<SchematronTest> tests = new ArrayList<>();
    for (DynamicVariable var : rule.findReferencedDynamicVariables()) {
      tests.add(new SchematronAssert.NoApiError(rule, var, this.context));
    }
    for (var variable : rule.getAutoGeneratedVariables()) {
      tests.add(new SchematronAssert.NoApiError(rule, variable, this.context));
    }

    // Main assert/report — guarded by the error asserts above.
    if (rule instanceof ReportRule) {
      tests.add(new SchematronReport(rule, this.context));
    } else {
      tests.add(new SchematronAssert(rule, this.context));
    }

    return tests;
  }

  /** Used by pattern.ftl */
  public String getContext() {
    return this.context.absolutePath().getScript();
  }

  /** Used by pattern.ftl */
  public List<SchematronLet> getLetElements() {
    return this.letElements;
  }

  /** Returns let elements promoted to pattern scope (WITH-before-context variables). */
  public List<SchematronLet> getPromotedLetElements() {
    return this.promotedLetElements;
  }

  /** Used by pattern.ftl */
  public List<SchematronTest> getTests() {
    return this.tests;
  }

  /** Returns true if this rule has at least one test. */
  public boolean hasTests() {
    return !this.tests.isEmpty();
  }

  /**
   * Returns true if this rule has at least one test matching the given rule natures.
   *
   * @param ruleNatures The set of rule natures to include
   * @return true if any test's nature is in the included set
   */
  public boolean hasTestsFor(final Set<RuleNature> ruleNatures) {
    return this.tests.stream().anyMatch(t -> ruleNatures.contains(t.getRuleNature()));
  }

  /**
   * Returns true if this rule has at least one test matching the given tags.
   * Used by FreeMarker templates.
   *
   * @param tags The list of tags to include
   * @return true if any test's tag is in the list
   */
  public boolean hasTestsFor(final List<String> tags) {
    return this.tests.stream().anyMatch(t -> tags.contains(t.getTag()));
  }

  /**
   * Returns diagnostics for tests that need them (where subject differs from context).
   */
  public Map<String, SchematronDiagnostic> getDiagnostics() {
    Map<String, SchematronDiagnostic> diagnostics = new LinkedHashMap<>();
    for (SchematronTest test : this.tests) {
      SchematronDiagnostic diagnostic = test.getDiagnostic();
      if (diagnostic != null) {
        diagnostics.put(diagnostic.getId(), diagnostic);
      }
    }
    return diagnostics;
  }
}
