/*
 * Copyright 2025 European Union
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the European
 * Commission – subsequent versions of the EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence
 * is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the Licence for the specific language governing permissions and limitations under
 * the Licence.
 */
package eu.europa.ted.efx.model.variables;

import eu.europa.ted.efx.model.expressions.Expression;
import eu.europa.ted.efx.model.expressions.scalar.BooleanExpression;
import eu.europa.ted.efx.model.expressions.scalar.DynamicExpression;
import eu.europa.ted.efx.model.rules.RuleSeverity;

/**
 * A variable whose value is computed by a dynamic function call.
 *
 * The initialization expression is the raw dynamic function call (e.g., {@code efx:call-api(...)}).
 * The reference expression compares the result to 1 (e.g., {@code $varName = 1}),
 * since the dynamic function returns a tri-state integer: 1 = true, 0 = false, -1 = error.
 *
 * Carries the API metadata needed for error handling (endpoint, error severity, label).
 */
public class DynamicVariable extends Variable {

    public final String endpointName;
    private final RuleSeverity errorSeverity;
    private final String errorLabel;

    public DynamicVariable(String name, Expression declarationExpression,
        DynamicExpression initializationExpression, BooleanExpression referenceExpression,
        String endpointName, RuleSeverity errorSeverity, String errorLabel) {
        super(name, declarationExpression, initializationExpression, referenceExpression);
        this.endpointName = endpointName;
        this.errorSeverity = errorSeverity;
        this.errorLabel = errorLabel;
    }

    public RuleSeverity errorSeverity() {
        return this.errorSeverity;
    }

    public String errorLabel() {
        return this.errorLabel;
    }

    public String identity() {
        return this.name;
    }

    /**
     * An auto-generated {@link DynamicVariable} created when a dynamic function is called
     * inline in a rule expression (e.g., {@code ?check-buyer(BT-00-Identifier)}).
     *
     * Unlike a user-declared {@link DynamicVariable}, this has an auto-generated
     * name (e.g., {@code __apiResult1}) and needs its own {@code <let>} declaration
     * in the Schematron rule output.
     */
    public static class AutoGenerated extends DynamicVariable {

        private final int index;

        public AutoGenerated(int index, String name, Expression declarationExpression,
            DynamicExpression initializationExpression, BooleanExpression referenceExpression,
            String endpointName, RuleSeverity errorSeverity, String errorLabel) {
            super(name, declarationExpression, initializationExpression, referenceExpression,
                endpointName, errorSeverity, errorLabel);
            this.index = index;
        }

        public int index() { return this.index; }

        @Override
        public String identity() {
            return String.valueOf(this.index);
        }
    }
}
