/*
 * Copyright 2025 European Union
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the European
 * Commission – subsequent versions of the EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence
 * is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the Licence for the specific language governing permissions and limitations under
 * the Licence.
 */
package eu.europa.ted.efx.model.rules;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import eu.europa.ted.efx.model.Context;
import eu.europa.ted.efx.model.ParsedEntity;
import eu.europa.ted.efx.model.expressions.scalar.BooleanExpression;
import eu.europa.ted.efx.model.variables.DynamicVariable;
import eu.europa.ted.efx.model.variables.Variable;

public class ValidationRule implements ParsedEntity {

    RuleSet ruleSet;
    String id;
    Context subject;
    RuleSeverity severity;
    RuleNature nature = RuleNature.STATIC;
    BooleanExpression condition;
    BooleanExpression invertedCondition;
    BooleanExpression expression;
    BooleanExpression invertedConditionOrExpression;
    NoticeSubtypeRange noticeSubtypeRange;
    String flag;
    RuleScope scope = RuleScope.ANY;
    List<DynamicVariable.AutoGenerated> autoGeneratedVariables = new ArrayList<>();

    public ValidationRule(final RuleSet ruleSet) {
        this.ruleSet = ruleSet;
    }

    public RuleSet getRuleSet() {
        return this.ruleSet;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }

    public void setSubject(Context subject) {
        this.subject = subject;
    }
    public Context getSubject() {
        return this.subject;
    }

    public void setSeverity(RuleSeverity severity) {
        this.severity = severity;
    }
    public RuleSeverity getSeverity() {
        return this.severity;
    }

    public void setNature(RuleNature nature) {
        this.nature = nature;
    }
    public RuleNature getNature() {
        return this.nature;
    }

    public void setCondition(BooleanExpression condition, BooleanExpression invertedCondition, BooleanExpression invertedConditionOrExpression) {
        this.condition = condition;
        this.invertedCondition = invertedCondition;
        this.invertedConditionOrExpression = invertedConditionOrExpression;
    }

    public BooleanExpression getCondition() {
        return this.condition;
    }

    public BooleanExpression getInvertedCondition() {
        return this.invertedCondition;
    }

    public void setExpression(BooleanExpression expression, BooleanExpression invertedConditionOrExpression) {
        this.expression = expression;
        this.invertedConditionOrExpression = invertedConditionOrExpression;
    }

    public BooleanExpression getExpression() {
        return this.expression;
    }

    public BooleanExpression getInvertedConditionOrExpressionCombination() {
        return this.invertedConditionOrExpression;
    }

    public void setNoticeSubtypeRange(NoticeSubtypeRange noticeSubtypeRange) {
        this.noticeSubtypeRange = noticeSubtypeRange;
    }
    public NoticeSubtypeRange getNoticeSubtypeRange() {
        return this.noticeSubtypeRange;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }
    public String getFlag() {
        return this.flag;
    }

    public void setScope(RuleScope scope) {
        this.scope = scope;
    }
    public RuleScope getScope() {
        return this.scope;
    }

    public void addAutoGeneratedVariable(DynamicVariable.AutoGenerated variable) {
        this.autoGeneratedVariables.add(variable);
        this.nature = RuleNature.DYNAMIC;
    }

    public List<DynamicVariable.AutoGenerated> getAutoGeneratedVariables() {
        return this.autoGeneratedVariables;
    }

    public boolean hasAutoGeneratedVariables() {
        return !this.autoGeneratedVariables.isEmpty();
    }

    public <T extends Variable> List<T> findReferencedVariables(final List<T> variables) {
        if (variables.isEmpty()) {
            return variables;
        }
        String script = this.invertedConditionOrExpression.getScript();
        return variables.stream()
                .filter(var -> Pattern.compile("\\$" + Pattern.quote(var.name) + "(?![\\w-])")
                        .matcher(script).find())
                .collect(Collectors.toList());
    }

    public List<DynamicVariable> findReferencedDynamicVariables() {
        return this.findReferencedVariables(this.ruleSet.getAllVariables()).stream()
                .flatMap(var -> {
                    if (var instanceof DynamicVariable) {
                        return Stream.of((DynamicVariable) var);
                    }
                    return var.getDynamicDependencies().stream();
                })
                .distinct()
                .collect(Collectors.toList());
    }

    public boolean isUniversal() {
        return this.noticeSubtypeRange != null && this.noticeSubtypeRange.isUniversal();
    }

    public boolean isForNoticeSubtype(String noticeSubtype) {
        return this.noticeSubtypeRange != null
            && this.noticeSubtypeRange.asList().contains(noticeSubtype);
    }

    public boolean isForPostValidation() {
        return this.scope != RuleScope.PRE;
    }

    public boolean isForPreValidation() {
        return this.scope != RuleScope.POST;
    }

}
