/*
 * Copyright 2022 European Union
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the European
 * Commission – subsequent versions of the EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence
 * is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the Licence for the specific language governing permissions and limitations under
 * the Licence.
 */
package eu.europa.ted.efx.interfaces;

import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.commons.lang3.tuple.Pair;
import eu.europa.ted.efx.model.expressions.Expression;
import eu.europa.ted.efx.model.expressions.PathExpression;
import eu.europa.ted.efx.model.expressions.TypedExpression;
import eu.europa.ted.efx.model.expressions.scalar.NumericExpression;
import eu.europa.ted.efx.model.expressions.scalar.StringExpression;
import eu.europa.ted.efx.model.templates.Conditional;
import eu.europa.ted.efx.model.templates.Markup;
import eu.europa.ted.efx.model.types.EfxDataType;

/**
 * The role of this interface is to allow the reuse of the EfxTemplateTranslator to generate
 * markup for any target template language,
 * 
 * The methods provided by this interface cover two needs: 
 * a) Take {@link Expression} as a parameters and generate the target template markup 
 *    necessary for rendering; and 
 * b) Take multiple {@link Markup} objects already generated by other method calls and
 *    generate the markup to properly combine them in the target template.
 */
public interface MarkupGenerator {


    /**
     * Given a body (main content) and a set of fragments, this method returns the
     * full content of the
     * target template file.
     * 
     * @param globals   the global variables and functions to be included in the
     *                  template file.
     * @param mainSection   the main section (body) of the template.
     * @param summarySection the summary section of the template.
     * @param navigationSection the navigation section of the template.
     * @param fragments the fragments to be included in the template file.
     * @return          the full content of the target template file.
     */
    Markup composeOutputFile(List<Markup> globals, final List<Markup> mainSection, final List<Markup> summarySection, final List<Markup> navigationSection, final List<Markup> fragments);

    /**
     * Given a body (main content) and a set of fragments, this method returns the
     * full content of the target template file.
     * 
     * @deprecated This method is deprecated and will be removed in future versions.
     *             Use {@link #composeOutputFile(List, List, List, List, List)} instead.
     *             We are keeping the method temporarily to prevent build errors.
     *             This method is being deprecated as of version 2.0.0-alpha.6 and
     *             will be removed before version 2.0.0 is released
     *  
     * @param content   the body (main content) of the template.
     * @param fragments the fragments to be included in the template file.
     * @return          the full content of the target template file.
     */
    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default public Markup composeOutputFile(final List<Markup> content, final List<Markup> fragments) {
        return this.composeOutputFile(List.of(), content, List.of(), List.of(), fragments);
    }

    /**
     * Renders the markup necessary to declare and initialize the variable making it
     * available at runtime.
     *
     * The type and whether the variable is a sequence are derived from the initialiser's data type.
     *
     * @param name        The name of the variable to be declared.
     * @param initialiser The typed expression used to initialize the variable.
     * @return            A {@link Markup} object that contains the variable declaration.
     */
    Markup renderVariableDeclaration(final String name, final TypedExpression initialiser);

    /**
     * Renders the markup necessary to declare and initialize the variable making it
     * available at runtime.
     *
     * @deprecated Use {@link #renderVariableDeclaration(String, TypedExpression)} instead.
     *             This method is being deprecated as of version 2.0.0-alpha.6 and
     *             will be removed before version 2.0.0 is released.
     *
     * @param type        A subclass of {@link EfxDataType} specifying the type of
     *                    the variable.
     * @param name        The name of the variable to be declared.
     * @param initialiser The expression used to initialize the variable.
     * @return            A {@link Markup} object that contains the variable declaration.
     */
    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default Markup renderVariableDeclaration(final Class<? extends EfxDataType> type, final String name, final Expression initialiser) {
        assert initialiser instanceof TypedExpression : "Initialiser must be a TypedExpression";
        return renderVariableDeclaration(name, (TypedExpression) initialiser);
    }

    /**
     * Renders the markup necessary to declare and initialise a dictionary .
     *
     * @param name  The name of the dictionary to be declared.
     * @param match The path expression to be indexed.
     *              Each of the values matched by this path will be added
     *              to the dictionary with the corresponding key.
     * @param key   The expression to calculate the keys. To initialise the
     *              dictionary the key needs to be calculated relative to
     *              the match.
     * @return A {@link Markup} object that declares the dictionary.
     */
    Markup renderDictionaryDeclaration(final String name, final PathExpression match, final StringExpression key);

    /**
     * Renders the Markup necessary to make the function available at runtime.
     * The return type is derived from the expression's data type.
     *
     * @param name       The name of the function.
     * @param parameters The parameters of the function as a map from parameter name to its EFX data type.
     * @param expression The function body expression (typed, so return type can be derived).
     * @return           A Markup object that declares the function.
     */
    Markup renderFunctionDeclaration(final String name, final Map<String, Class<? extends EfxDataType>> parameters, final TypedExpression expression);

    /**
     * Renders the Markup necessary to make the function available at runtime.
     *
     * @deprecated Use {@link #renderFunctionDeclaration(String, Map, TypedExpression)} instead.
     *             This method is being deprecated as of version 2.0.0-alpha.6 and
     *             will be removed before version 2.0.0 is released.
     *
     * @param type       The return type of the function.
     * @param name       The name of the function.
     * @param parameters The parameters of the function as a map from parameter name to its EFX data type.
     * @param expression The function body expression.
     * @return           A Markup object that declares the function.
     */
    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default Markup renderFunctionDeclaration(final Class<? extends EfxDataType> type, final String name, final Map<String, Class<? extends EfxDataType>> parameters, final Expression expression) {
        assert expression instanceof TypedExpression : "Expression must be a TypedExpression";
        return renderFunctionDeclaration(name, parameters, (TypedExpression) expression);
    }


    /**
     * Given an expression (which will eventually, at runtime, evaluate to the value
     * of a field), this
     * method returns the template code that dereferences it (retrieves the value)
     * in the target
     * template.
     * 
     * @param   variableExpression the expression to be evaluated and rendered.
     * @param   translatorContext additional context information provided by the template translator.
     * @return  the template code that dereferences the expression in the target
     *          template.
     */
    Markup renderVariableExpression(final Expression variableExpression, final TranslatorContext translatorContext);

    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default public Markup renderVariableExpression(final Expression variableExpression) {
        return this.renderVariableExpression(variableExpression, TranslatorContext.DEFAULT);
    }

    /**
     * Given a label key (which will eventually, at runtime, be dereferenced to a
     * label text), this
     * method returns the template code that renders this label in the target
     * template language.
     * 
     * @param key     the label key to be dereferenced.
     * @param translatorContext additional context information provided by the template
     *                translator.
     * @return the template code that renders the label in the target template
     *         language.
     */
    Markup renderLabelFromKey(final StringExpression key, final TranslatorContext translatorContext);

    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default public Markup renderLabelFromKey(final StringExpression key) {
            return this.renderLabelFromKey(key, TranslatorContext.DEFAULT);
    }

    /**
     * Given a label key (which will eventually, at runtime, be dereferenced to a
     * label text), this
     * method returns the template code that renders this label in the target
     * template language.
     * 
     * @param key      the label key to be dereferenced.
     * @param quantity a numeric quantity used to decide if the label needs to be
     *                 pluralized.
     * @param translatorContext  additional context information provided by the template translator.
     * @return         the template code that renders the label in the target template
     *                 language.
     */
    Markup renderLabelFromKey(final StringExpression key, final NumericExpression quantity, final TranslatorContext translatorContext);

    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default public Markup renderLabelFromKey(final StringExpression key, final NumericExpression quantity) {
        return this.renderLabelFromKey(key, quantity, TranslatorContext.DEFAULT);
    }

    /**
     * Given an expression (which will eventually, at runtime, be evaluated to a
     * label key and
     * subsequently dereferenced to a label text), this method returns the template
     * code that renders
     * this label in the target template language.
     * 
     * @param   expression the expression that returns the label key.
     * @param   translatorContext additional context information provided by the template translator.
     * @return  the template code that renders the label in the target template
     *          language.
     */
    Markup renderLabelFromExpression(final Expression expression, final TranslatorContext translatorContext);

    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default public Markup renderLabelFromExpression(final Expression expression) {
        return this.renderLabelFromExpression(expression, TranslatorContext.DEFAULT);
    }

    /**
     * Given an expression (which will eventually, at runtime, be evaluated to a
     * label key and
     * subsequently dereferenced to a label text), this method returns the template
     * code that renders
     * this label in the target template language.
     * 
     * @param expression the expression that returns the label key.
     * @param quantity   a numeric quantity used to decide if the label needs to be
     *                   pluralized.
     * @param translatorContext   additional context information provided by the template translator.
     * @return           the template code that renders the label in the target template
     *                   language.
     */
    Markup renderLabelFromExpression(final Expression expression, final NumericExpression quantity, final TranslatorContext translatorContext);

    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default public Markup renderLabelFromExpression(final Expression expression, final NumericExpression quantity) {
        return this.renderLabelFromExpression(expression, quantity, TranslatorContext.DEFAULT);
    }

    /**
     * Given a string of free text, this method returns the template code that adds
     * this text in the target template.
     *  
     * The EfxTemplateTranslator will first escape the text using 
     * {@link #escapeSpecialCharacters(String)} and then pass the escaped text to this method.
     * 
     * @param   freeText the free text to be rendered.
     * @param   translatorContext additional context information provided by the template translator.
     * @return  the template code that adds this text in the target template.
     */
    Markup renderFreeText(final String freeText, final TranslatorContext translatorContext);

    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default public Markup renderFreeText(final String freeText) {
        return this.renderFreeText(freeText, TranslatorContext.DEFAULT);
    }

    /**
     * Given a label and a URL, this method returns the template code that renders
     * a hyperlink in the target template language.
     *
     * @param label  the label to be displayed for the hyperlink.
     * @param url    the URL to be linked to.
     * @param translatorContext additional context information provided by the template translator.
     * @return the template code that renders the hyperlink in the target template language.
     */
    Markup renderHyperlink(final Markup label, final StringExpression url, final TranslatorContext translatorContext);


    /**
     * Returns the markup that represents a line break in the target template.
     * 
     * For example, in EFX to XSLT, translation this would return a {@code <br/>} HTML
     * element if your target is rendering HTML, or an {@code <xsl:text>&#10;</xsl:text>}
     * (which is the XSLT equivalent of a line feed) if you are not targeting HTML.
     * 
     * @return the markup that represents a line break in the target template.
     */
    Markup renderLineBreak(final TranslatorContext translatorContext);

    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default public Markup renderLineBreak() {
        return this.renderLineBreak(TranslatorContext.DEFAULT);
    }

    /**
     * Given a fragment name (identifier) and some pre-rendered content, this method
     * returns the code that encapsulates it in the target template.
     *
     * @deprecated This method is deprecated and will be removed in future versions.
     *             Use {@link #composeFragmentDefinition(String, String, Set, Markup, Markup, Set,
     *             TranslatorContext)} instead. We are keeping the method temporarily to prevent
     *             build errors. This method is being deprecated as of version 2.0.0-alpha.6 and
     *             will be removed before version 2.0.0 is released. The default implementation
     *             provided here only throws UnsupportedOperationException to prevent accidental
     *             use of this method. The EfxTemplateTranslator will not call this method.
     *
     * @param name          the name of the fragment.
     * @param number        the outline number of the fragment.
     * @param content       the content of the fragment.
     * @param parameters    the parameters of the fragment.
     * @return              the code that encapsulates the fragment in the target template.
     */
    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default Markup composeFragmentDefinition(final String name, String number, Markup content,
            Set<String> parameters) {
        throw new UnsupportedOperationException(
                "This method is deprecated and will be removed in future versions. Use composeFragmentDefinition(String, String, Set<Conditional>, Markup, Markup, Set<Parameter>) instead.");
    }    
    
    /**
     * Given a fragment name (identifier) and some pre-rendered content, this method
     * returns the code that encapsulates it in the target template.
     *
     * @param name              the name of the fragment.
     * @param number            the outline number of the fragment.
     * @param conditionals      the conditionals of the fragment.
     * @param content           the content of the fragment.
     * @param children          the children of the fragment.
     * @param parameters        the parameters of the fragment.
     * @param translatorContext additional context information provided by the template translator.
     * @return                  the code that encapsulates the fragment in the target template.
     */
    Markup composeFragmentDefinition(final String name, final String number, final Set<Conditional> conditionals, final Markup content, final Markup children,
            final Set<Parameter> parameters, final TranslatorContext translatorContext);

    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default public Markup composeFragmentDefinition(final String name, String number, Set<Conditional> conditionals,
                    Markup content, Markup children,
                    Set<Parameter> parameters) {
            return composeFragmentDefinition(name, number, conditionals, content, children, parameters,
                            TranslatorContext.DEFAULT);
    }


    /**
     * Given a fragment name (identifier), and an evaluation context, this method
     * returns the code that invokes the fragment.
     * 
     * The EfxTemplateTranslator will call this method to generate the
     * fragment invocation code and then will pass the generated Markup to the
     * {@link #renderContextLoop(PathExpression, Markup, Set)}.
     * 
     * In EFX to XSLT translation, this method would generate the xsl:call-template
     * that will invoke the fragment.
     * 
     * @param name      the name of the fragment.
     * @param arguments the arguments of the fragment.
     * @param translatorContext   additional context information provided by the template translator.
     * @return          the code that invokes (uses) the fragment.
     */
    Markup renderFragmentInvocation(final String name, final Set<Argument> arguments, final TranslatorContext translatorContext);

    /**
     * Given a fragment name (identifier), and an evaluation context, this method
     * returns the code that invokes the fragment.
     * 
     * The EfxTemplateTranslator will call this method to generate the
     * fragment invocation code and then will pass the generated Markup to the
     * {@link #renderContextLoop(PathExpression, Markup, Set)}.
     * 
     * In EFX to XSLT translation, this method would generate the xsl:call-template
     * that will invoke the fragment.
     * 
     * @deprecated This method is deprecated and will be removed in future versions.
     *             Use {@link #renderFragmentInvocation(String, Set, TranslatorContext)}
     *             instead.
     * 
     * @param name      the name of the fragment.
     * @param arguments the arguments of the fragment.
     * @return          the code that invokes (uses) the fragment.
     */
    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default public Markup renderFragmentInvocation(final String name, final Set<Argument> arguments) {
        return this.renderFragmentInvocation(name, arguments, TranslatorContext.DEFAULT);
    }

    /**
     * Given a fragment name (identifier), and an evaluation context, this method
     * returns the code that invokes the fragment.
     * @deprecated  This method is deprecated and will be removed in future versions.
     *              Use {@link #renderFragmentInvocation(String, Set, TranslatorContext)} instead.
     *              We are keeping the method temporarily to prevent build errors.
     *              This method is being deprecated as of version 2.0.0-alpha.6 and
     *              will be removed before version 2.0.0 is released.
     *              The default implementation provided here only throws
     *              UnsupportedOperationException to prevent accidental use of this method.
     *              The EfxTemplateTranslator will not call this method.
     *
     * @param name      the name of the fragment.
     * @param context   the context of the fragment.
     * @param variables the variables of the fragment.
     * @return          the code that invokes (uses) the fragment.
     */
    @Deprecated(since = "2.0.0-alpha.6", forRemoval = true)
    default Markup renderFragmentInvocation(final String name, final PathExpression context,
            final Set<Pair<String, String>> variables) {
        throw new UnsupportedOperationException(
                "This method is deprecated and will be removed in future versions. Use renderFragmentInvocation(String, Set<Argument>) instead.");
    }


    /**
     * Given an evaluation context, and some pre-rendered content, this method returns the code that 
     * iterates over the context and repeats the content for each item in the context.
     * As of version 2.0.0-alpha.6, the method composeFragmentInvocation has been
     * split into two methods:
     * 1. {@link #renderFragmentInvocation(String, Set, TranslatorContext)}
     *    for rendering the fragment invocation itself, which is used by the
     *    context loop.
     * 2. {@link #renderContextLoop(PathExpression, Markup, Set)}
     *    for rendering the context loop that invokes the fragment.
     * 
     * The EfxTemplateTranslator will call these two methods in sequence to generate the
     * complete template code for a fragment. The first method will generate the
     * fragment definition and the second method will generate the code that invokes it
     * in a context loop.
     * 
     * In EFX to XSLT translation, this method would generate the xsl:for-each that will loop
     * over the context path expression and invoke the fragment for each item in the loop.
     * 
     * @param context   the context path expression for the loop.
     * @param content   the content of the fragment.
     * @param arguments the arguments to pass to the fragment.
     * @return the code that invokes (uses) the fragment in a context loop.
     */
    Markup renderContextLoop(final PathExpression context, final Markup content,
            final Set<Argument> arguments);

    /**
     * Returns the target template language equivalent for the given EFX data type.
     * 
     * For example, in EFX to XSLT translation this would be used to specify 
     * the type of an xsl:variable or the return type of an xsl:function by returning 
     * "xs:string" for {@link eu.europa.ted.efx.model.types.EfxDataType.String}, or
     * "xs:decimal" for {@link eu.europa.ted.efx.model.types.EfxDataType.Number}.
     * 
     * @param   type the EFX data type to convert.
     * @return  a {@link Markup} object representing the equivalent type in the
     *          target template language.
     */
    Markup getEfxDataTypeEquivalent(Class<? extends EfxDataType> type);

    /**
     * Escapes special characters in the given text. Used to make sure that
     * special characters in free-text do not interfere with the target template.
     * 
     * The EfxTemplateTranslator will call this method to escape special characters
     * in free-text before passing it to {@link #renderFreeText(String, TranslatorContext)}.
     * 
     * @param   text the text containing characters that may need to be escaped.
     * @return  the text with special characters properly escaped for the target
     *          template language.
     */
    String escapeSpecialCharacters(String text);
}
