/*
 * Copyright 2026 European Union
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the European
 * Commission – subsequent versions of the EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence
 * is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the Licence for the specific language governing permissions and limitations under
 * the Licence.
 */
package eu.europa.ted.efx.model.rules;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;

import org.junit.jupiter.api.Test;

import eu.europa.ted.efx.model.expressions.scalar.BooleanExpression;
import eu.europa.ted.efx.model.expressions.scalar.DynamicExpression;
import eu.europa.ted.efx.model.variables.DynamicVariable;

class ValidationRuleTest {

  private DynamicVariable createDynamicVariable(final String name) {
    return new DynamicVariable(name,
        new BooleanExpression(""),
        new DynamicExpression(""),
        new BooleanExpression("$" + name + " = 1"),
        "default", RuleSeverity.ERROR, null);
  }

  private final RuleSet testRuleSet = new RuleSet(new ValidationStage("test", new ValidationPlan()));

  private ValidationRule createRuleWithExpression(final String script) {
    ValidationRule rule = new ValidationRule(this.testRuleSet);
    rule.setExpression(new BooleanExpression(script), new BooleanExpression(script));
    return rule;
  }

  @Test
  void findReferencedVariables_exactMatch() {
    ValidationRule rule = this.createRuleWithExpression("$foo = 1");
    DynamicVariable foo = this.createDynamicVariable("foo");

    assertEquals(List.of(foo), rule.findReferencedVariables(List.of(foo)));
  }

  @Test
  void findReferencedVariables_noMatch() {
    ValidationRule rule = this.createRuleWithExpression("$bar = 1");
    DynamicVariable foo = this.createDynamicVariable("foo");

    assertTrue(rule.findReferencedVariables(List.of(foo)).isEmpty());
  }

  @Test
  void findReferencedVariables_doesNotMatchPrefix() {
    ValidationRule rule = this.createRuleWithExpression("$foobar = 1");
    DynamicVariable foo = this.createDynamicVariable("foo");

    assertTrue(rule.findReferencedVariables(List.of(foo)).isEmpty());
  }

  @Test
  void findReferencedVariables_doesNotMatchWithTrailingDigit() {
    ValidationRule rule = this.createRuleWithExpression("$foo10 = 1");
    DynamicVariable foo1 = this.createDynamicVariable("foo1");

    assertTrue(rule.findReferencedVariables(List.of(foo1)).isEmpty());
  }

  @Test
  void findReferencedVariables_doesNotMatchWithTrailingUnderscore() {
    ValidationRule rule = this.createRuleWithExpression("$foo_bar = 1");
    DynamicVariable foo = this.createDynamicVariable("foo");

    assertTrue(rule.findReferencedVariables(List.of(foo)).isEmpty());
  }

  @Test
  void findReferencedVariables_doesNotMatchWithTrailingDash() {
    ValidationRule rule = this.createRuleWithExpression("$foo-bar = 1");
    DynamicVariable foo = this.createDynamicVariable("foo");

    assertTrue(rule.findReferencedVariables(List.of(foo)).isEmpty());
  }

  @Test
  void findReferencedVariables_matchesAtEndOfScript() {
    ValidationRule rule = this.createRuleWithExpression("something or $foo");
    DynamicVariable foo = this.createDynamicVariable("foo");

    assertEquals(List.of(foo), rule.findReferencedVariables(List.of(foo)));
  }

  @Test
  void findReferencedVariables_matchesFollowedByOperator() {
    ValidationRule rule = this.createRuleWithExpression("($foo=1) or ($bar=1)");
    DynamicVariable foo = this.createDynamicVariable("foo");
    DynamicVariable bar = this.createDynamicVariable("bar");

    assertEquals(List.of(foo, bar), rule.findReferencedVariables(List.of(foo, bar)));
  }

  @Test
  void findReferencedVariables_matchesFollowedByParenthesis() {
    ValidationRule rule = this.createRuleWithExpression("not($foo)");
    DynamicVariable foo = this.createDynamicVariable("foo");

    assertEquals(List.of(foo), rule.findReferencedVariables(List.of(foo)));
  }

  @Test
  void findReferencedVariables_matchesFollowedBySpace() {
    ValidationRule rule = this.createRuleWithExpression("$foo = 1");
    DynamicVariable foo = this.createDynamicVariable("foo");

    assertEquals(List.of(foo), rule.findReferencedVariables(List.of(foo)));
  }

  @Test
  void findReferencedVariables_autoGeneratedNamePartialMatch() {
    ValidationRule rule = this.createRuleWithExpression("($__apiResult10 = -1) or ($__apiResult1 = 1)");
    DynamicVariable result1 = this.createDynamicVariable("__apiResult1");
    DynamicVariable result10 = this.createDynamicVariable("__apiResult10");

    assertEquals(List.of(result1, result10), rule.findReferencedVariables(List.of(result1, result10)));
  }

  @Test
  void findReferencedVariables_emptyList() {
    ValidationRule rule = this.createRuleWithExpression("$foo = 1");

    assertTrue(rule.findReferencedVariables(List.of()).isEmpty());
  }

  @Test
  void findReferencedVariables_selectsOnlyReferenced() {
    ValidationRule rule = this.createRuleWithExpression("$alpha = 1 and $gamma = 1");
    DynamicVariable alpha = this.createDynamicVariable("alpha");
    DynamicVariable beta = this.createDynamicVariable("beta");
    DynamicVariable gamma = this.createDynamicVariable("gamma");

    assertEquals(List.of(alpha, gamma), rule.findReferencedVariables(List.of(alpha, beta, gamma)));
  }
}
